### ISSUE TITLE
Wrong constant value for c6

### ISSUE THREAD

**Issue by mwittig** [nicolasgrancher/weather-js#1]
According [Wikipedia ](https://en.wikipedia.org/wiki/Heat_index) the value is −5.481717 x 10^−2

**Comment by mwittig** [comment]
See also my pull request #4 for issue #2. 
If you agree on this pull request you can simply close pull request #3 for the wrong constant issue.

**Comment by nicolasgrancher** [comment]
Hi Marcus.

Thx for your contribution. You're right it's easier to work with celcius constant.

#4 has been merged.
