### ISSUE TITLE
Using constants for Celsius

### ISSUE THREAD

**Issue by mwittig** [nicolasgrancher/weather-js#2]
I am wondering why you don't use the constants for Celsius. This way, you won't need the conversion of `Tc` to Fahrenheit and the conversion of `HI` to Celsius. The constants for Celsius can be found on the [German Wikipedia page](https://de.wikipedia.org/wiki/Hitzeindex). 

I am happy to file a PR on this if you agree on this

**Comment by nicolasgrancher** [comment]
Hi Marcus. 

Your #4 PR has been merged.

Thanks.
